version: "3.4"

services:
    test-web-api:
        build:
          context: .
          dockerfile: test.web.api/Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db

    jwt-service:
        build:
          context: .
          dockerfile: JWTService/Dockerfile
        ports:
          - "8090:80"

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"